# Generated by Django 4.1 on 2024-04-03 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_remove_comment_blogger_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_blogger",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_date",
            field=models.DateField(default="2024-04-01", verbose_name="Updated on"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="updated_date",
            field=models.DateField(default="2024-04-01", verbose_name="Updated on"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="blogger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
