# Generated by Django 4.1 on 2024-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_updated_date_alter_post_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated on"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated on"),
        ),
    ]
